print ('Trata-se do meu primeiro código na linguagem PYTHON')
print ('Este código calcula o saldo médio de 4 meses de uma conta corrente ')
n1 = int(input  ('Digite o saldo da conta em Janeiiro'))
n2 = int(input ('Digite o saldo da conta em Fevereiro'))
n3 = int(input ('Digite o saldo da conta em Março'))
n4 = int (input ('Digite o saldo da conta em Abril'))
soma = (n1+n2+n3+n4)
media = (soma/4)
print ('O saldo médio da conta corrente = ', media)